name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env variables for Docker builds
      run: |
        echo "::set-env name=DOCKER_CLI_EXPERIMENTAL::enabled"
        echo "::set-env name=DOCKERHUB_REPO::wipa"
        echo "::set-env name=BASE_IMG_JRE_DEFAULT::adoptopenjdk/openjdk8-openj9:alpine-slim"
        echo "::set-env name=BASE_IMG_JRE_ARM32V7::arm32v7/openjdk:11-jre-slim"
        echo "::set-env name=BASE_IMG_JRE_ARM64V8::arm64v8/openjdk:11-jre-slim"
    - name: Docker enable experimental feature
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        cat /etc/docker/daemon.json
    - name: Download qemu for multi-arch builds
      run: sudo apt-get install qemu-user-static
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - name: Build and push Docker Images
      run: >
        bash docker-build.sh
        ${{ env.DOCKERHUB_APACHE_REPO }}
        ${{ env.BASE_IMG_JRE_DEFAULT }}
        ${{ env.BASE_IMG_JRE_ARM32V7 }}
        ${{ env.BASE_IMG_JRE_ARM64V8 }}
